# Generated by Django 5.2.1 on 2025-05-21 11:39

from django.utils import timezone
from django.db import migrations
from django.contrib.auth import get_user_model


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_article_word_count'),
    ]
    
    def create_superuser(apps, schema_editor):
        User = get_user_model()

        if User.objects.exists():
            return 
        
        superuser = User.objects.create_superuser(
            username="example_username",
            email="example@example.com",
            password="example_password",
            last_login=timezone.now()
        )
        superuser.save()

    operations = [
        migrations.RunPython(create_superuser)
    ]

